name: "Naabu Action"
description: "A fast port scanner written in go with a focus on reliability and simplicity."
branding:
  icon: "activity"
  color: "blue"

inputs:
  host:
    description: "Host to perform port scan"
    required: true

  list:
    description: "List of hosts to perform port scan"
    required: false

  ports:
    description: "Ports to scan for (default - Top 100)"
    required: false

  output:
    description: "File to save output result"
    required: false
    default: "naabu.log"

  json:
    description: "Format to save of output file"
    required: false
    default: false

  rate:
    description: "Rate of port scan probes"
    required: false

  passive:
    description: "Perform passive port enumeration"
    required: false
    default: false

  flags:
    description: "Additional naabu CLI flags to use"
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'